### ISSUE TITLE
arch linux problems (python3.8)

### ISSUE THREAD

**Issue by s0me0ther** [atareao/cpu-g#12]
I had to cleanup two problems until i could get the package get to run on my notebook:

![image](https://user-images.githubusercontent.com/2334783/69372777-ae7ec400-0ca2-11ea-8463-6887f7d028a8.png)

- platform.dist AND platform.linux_distribution are not supported (Python 3.8.0)
-> use https://pypi.org/project/distro/ instead
- my battery stats filenames does have other names (which i changed in `investigator.py`):
![image](https://user-images.githubusercontent.com/2334783/69373008-2220d100-0ca3-11ea-89a9-5361dfd8c330.png)

Kindly regards

**Comment by atareao** [comment]
Fixed. Thanks for your report
